# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'GifExample' do

# pod 'CocoaGIF', :path => "../"
pod 'CocoaGIF', :podspec => 'https://github.com/joywek/CocoaGIF/blob/master/CocoaGIF.podspec'
pod 'AFNetworking'

end

